import {
  formatFiles,
  Tree,
  readJson,
  writeJson,
  joinPathFragments,
} from '@nx/devkit';
import { applicationGenerator } from '@nx/react';
import { GeneratorGeneratorSchema } from './schema';

export async function generatorGenerator(tree: Tree, options: GeneratorGeneratorSchema) {
  const mfeName = options.name;
  const port = options.port;
  const projectRoot = `apps/${mfeName}`;

  // 1. Scaffold base React + Vite application using Nx generator
  await applicationGenerator(tree, {
    name: mfeName,
    directory: projectRoot,
    style: 'css',
    bundler: 'vite',
    linter: 'eslint',
    unitTestRunner: 'none',
    e2eTestRunner: 'none',
    routing: true,
    strict: true,
  });

  // 2. Overwrite vite.config.ts with Module Federation setup
  const viteConfigContent = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { federation } from '@module-federation/vite';

export default defineConfig({
  server: {
    port: ${port},
    origin: 'http://localhost:${port}',
  },
  preview: {
    port: ${port + 100},
  },
  plugins: [
    react(),
    tailwindcss(),
    federation({
      name: '${mfeName.replace(/-/g, '')}',
      filename: 'remoteEntry.js',
      manifest: true,
      dts: false,
      exposes: {
        './App': './src/App.tsx',
      },
      shared: {
        react: { singleton: true, requiredVersion: '^19.0.0' },
        'react-dom': { singleton: true, requiredVersion: '^19.0.0' },
        'react/': { singleton: true },
        'react-dom/': { singleton: true },
      },
    }),
  ],
  build: {
    target: 'chrome89',
    modulePreload: false,
    minify: true,
  },
});
`;
  tree.write(joinPathFragments(projectRoot, 'vite.config.ts'), viteConfigContent);

  // 3. Setup Tailwind v4 in index.css
  const indexCssContent = `@import "tailwindcss";
@import "../../../libs/ui-kit/src/styles/theme.css";

/* MFE-specific styles go here */
`;
  tree.write(joinPathFragments(projectRoot, 'src/styles.css'), indexCssContent);
  
  // Clean up default Nx generated components
  tree.delete(joinPathFragments(projectRoot, 'src/app'));

  // 4. Overwrite App.tsx
  const appTsxContent = `import { Card, CardContent } from '@my-saas/ui-kit';

export function App() {
  return (
    <div className="p-8 max-w-4xl mx-auto">
      <Card variant="elevated" className="bg-white">
        <CardContent className="p-8">
          <h1 className="text-3xl font-bold text-primary-900 mb-4">
            Hello from ${mfeName}!
          </h1>
          <p className="text-neutral-600 mb-6">
            This Micro Frontend was auto-generated by the internal platform generator.
          </p>
          <div className="bg-primary-50 p-4 rounded-lg border border-primary-100 flex items-center justify-between">
            <span className="text-sm font-medium text-primary-800">Status</span>
            <span className="px-3 py-1 bg-success/10 text-success text-xs font-bold rounded-full">
              Federated & Ready
            </span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

export default App;
`;
  tree.write(joinPathFragments(projectRoot, 'src/App.tsx'), appTsxContent);
  // remove the default Nx spec file since we disabled tests
  if (tree.exists(joinPathFragments(projectRoot, 'src/App.spec.tsx'))) {
    tree.delete(joinPathFragments(projectRoot, 'src/App.spec.tsx'));
  }

  // 5. Overwrite main.tsx for standalone dev
  const mainTsxContent = `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router';
import './styles.css';
import { App } from './App';

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error('Failed to find the root element');

createRoot(rootElement).render(
  <StrictMode>
    <BrowserRouter>
      <div className="min-h-screen bg-neutral-50 p-4">
        <header className="mb-8 pl-4">
          <p className="text-sm text-neutral-500 font-medium">Standalone Mode (Port ${port})</p>
        </header>
        <App />
      </div>
    </BrowserRouter>
  </StrictMode>
);
`;
  tree.write(joinPathFragments(projectRoot, 'src/main.tsx'), mainTsxContent);

  // 6. Update shell's remotes.json registry
  const remotesJsonPath = 'apps/shell/public/remotes.json';
  if (tree.exists(remotesJsonPath)) {
    const registry = readJson(tree, remotesJsonPath);
    registry.remotes = registry.remotes || {};
    registry.remotes[mfeName] = {
      name: mfeName.replace(/-/g, ''), // safe variable name for MF
      entry: `http://localhost:${port}/mf-manifest.json`,
      activeWhenPath: `/${mfeName}`,
      exposes: {
        "./App": "./App"
      }
    };
    writeJson(tree, remotesJsonPath, registry);
  }

  // 7. Update shell's vite.config.ts to inject the new remote at build time
  const shellVitePath = 'apps/shell/vite.config.ts';
  if (tree.exists(shellVitePath)) {
    let shellViteContent = tree.read(shellVitePath, 'utf-8');
    if (shellViteContent) {
      // Find the remotes block and insert our new remote
      const remoteConfig = `${mfeName.replace(/-/g, '')}: {
          type: 'module',
          name: '${mfeName.replace(/-/g, '')}',
          entry: 'http://localhost:${port}/mf-manifest.json',
        },`;
      
      // Simple string injection right after "remotes: {"
      shellViteContent = shellViteContent.replace(
        /remotes:\s*\{/,
        `remotes: {\n        ${remoteConfig}`
      );
      tree.write(shellVitePath, shellViteContent);
    }
  }

  // 8. Add package.json with type: module for Vite/esbuild fix
  const packageJsonPath = joinPathFragments(projectRoot, 'package.json');
  const pkg = {
    name: mfeName,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      serve: `vite --port ${port}`,
      build: 'tsc -b && vite build',
      preview: `vite preview --port ${port + 100}`
    },
    dependencies: {
      '@my-saas/ui-kit': 'workspace:*',
      '@my-saas/shared-types': 'workspace:*',
      'react': '^19.0.0',
      'react-dom': '^19.0.0',
      'react-router': '^7.0.0'
    },
    devDependencies: {
      '@types/node': '^22.0.0',
      '@module-federation/vite': '^1.11.0',
      '@tailwindcss/vite': '^4.0.0',
      'tailwindcss': '^4.0.0',
      '@vitejs/plugin-react': '^4.5.0'
    }
  };
  writeJson(tree, packageJsonPath, pkg);

  // 9. Cleanup the scaffolded template files we didn't use from the bare generator scaffold
  if (tree.children(joinPathFragments(__dirname, 'files')).length > 0) {
    // The Nx generator command created standard template files in tools/src/generators/mfe/files
    // We don't actually need them since we dynamically overwrite content above.
    // We'll just leave them or ignore them since `generateFiles` is not called.
  }

  // 10. Update shell's vite-env.d.ts to declare the new module for TypeScript
  const shellEnvPath = 'apps/shell/src/vite-env.d.ts';
  if (tree.exists(shellEnvPath)) {
    const envContent = tree.read(shellEnvPath, 'utf-8') || '';
    const declaration = `\ndeclare module '${mfeName.replace(/-/g, '')}/App' {
  const App: React.ComponentType;
  export default App;
}\n`;
    if (!envContent.includes(declaration)) {
      tree.write(shellEnvPath, envContent + declaration);
    }
  }

  await formatFiles(tree);
}

export default generatorGenerator;
